sudo: required
services:
  - docker

before_install: 
  - docker build -t xith/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true xith/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Docker-react-env-3"
  bucket_name: "elasticbeanstalk-ap-northeast-1-613946323628"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"